/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashboardCampaignsRouteImport } from './routes/_protected/dashboard/campaigns'
import { Route as ProtectedDashboardRecipientsIndexRouteImport } from './routes/_protected/dashboard/recipients/index'
import { Route as ProtectedDashboardRecipientsNewRouteImport } from './routes/_protected/dashboard/recipients/new'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardCampaignsRoute =
  ProtectedDashboardCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardRecipientsIndexRoute =
  ProtectedDashboardRecipientsIndexRouteImport.update({
    id: '/recipients/',
    path: '/recipients/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardRecipientsNewRoute =
  ProtectedDashboardRecipientsNewRouteImport.update({
    id: '/recipients/new',
    path: '/recipients/new',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/dashboard/campaigns': typeof ProtectedDashboardCampaignsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/recipients/new': typeof ProtectedDashboardRecipientsNewRoute
  '/dashboard/recipients/': typeof ProtectedDashboardRecipientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/dashboard/campaigns': typeof ProtectedDashboardCampaignsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/recipients/new': typeof ProtectedDashboardRecipientsNewRoute
  '/dashboard/recipients': typeof ProtectedDashboardRecipientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/dashboard/campaigns': typeof ProtectedDashboardCampaignsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/dashboard/recipients/new': typeof ProtectedDashboardRecipientsNewRoute
  '/_protected/dashboard/recipients/': typeof ProtectedDashboardRecipientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/api/auth/$'
    | '/dashboard/recipients/new'
    | '/dashboard/recipients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/api/auth/$'
    | '/dashboard/recipients/new'
    | '/dashboard/recipients'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/dashboard'
    | '/_protected/dashboard/campaigns'
    | '/api/auth/$'
    | '/_protected/dashboard/recipients/new'
    | '/_protected/dashboard/recipients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/campaigns': {
      id: '/_protected/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof ProtectedDashboardCampaignsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/recipients/': {
      id: '/_protected/dashboard/recipients/'
      path: '/recipients'
      fullPath: '/dashboard/recipients/'
      preLoaderRoute: typeof ProtectedDashboardRecipientsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/recipients/new': {
      id: '/_protected/dashboard/recipients/new'
      path: '/recipients/new'
      fullPath: '/dashboard/recipients/new'
      preLoaderRoute: typeof ProtectedDashboardRecipientsNewRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardCampaignsRoute: typeof ProtectedDashboardCampaignsRoute
  ProtectedDashboardRecipientsNewRoute: typeof ProtectedDashboardRecipientsNewRoute
  ProtectedDashboardRecipientsIndexRoute: typeof ProtectedDashboardRecipientsIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardCampaignsRoute: ProtectedDashboardCampaignsRoute,
  ProtectedDashboardRecipientsNewRoute: ProtectedDashboardRecipientsNewRoute,
  ProtectedDashboardRecipientsIndexRoute:
    ProtectedDashboardRecipientsIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
